name: Covidfrontend

on: [push]

jobs:
      
  CovidBuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set Node.js 12.x
      uses: actions/setup-node@master
      with:
        version: 12.x

    - name: Install dependencies
      run: | 
        yarn install
        
    - name: Run Build
      run: |
        yarn run build
   
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
            github_token: ${{ secrets.GH_TOKEN }}
            cname: covidharyana.com

